### ISSUE TITLE
max() arg is an empty sequence

### ISSUE THREAD

**Issue by liuzhongkun1** [noneplugin/nonebot-plugin-imageutils#11]
![image](https://user-images.githubusercontent.com/94948855/202363049-8393b328-dbe3-43cd-a69c-0a38e34bfb45.png)为什么会出现这样的报错呀！
![image](https://user-images.githubusercontent.com/94948855/202363120-1c2c7cd7-e073-4a7c-b668-0e7d58baa1e2.png)

**Comment by MeetWq** [comment]
`title`的内容是什么

**Comment by liuzhongkun1** [comment]
This is an auto vacation reply. Hi, I am so sorry. I may not reply in time. I will reply to you soon when I see it.——lzk
