### ISSUE TITLE
关于 BBCode标签 及其他问题

### ISSUE THREAD

**Issue by QwindF** [noneplugin/nonebot-plugin-imageutils#13]
你好 MeetWq，我在使用你的插件时遇到一些问题：
1. 用 [align=right] 标签的时候会自动切换到换行，并向右对齐。
![OU(957IGMK%)99O6WTWH3K7](https://user-images.githubusercontent.com/87116340/208246846-8827de67-1a6b-4de1-9b26-489017c995c7.PNG)
![J9V9II8)~MD0UZCH V VZD9](https://user-images.githubusercontent.com/87116340/208246855-d481287c-e153-40ee-98a8-750f77427671.png)

2. 我想在这个图片的上方或者前面拼接一张图片，请问有这个功能吗？
案例是我在做关于 mc ping 类的插件时，一般mc服务器会有一个类似网站的ico图标，我想让他拼接到我生成图片的前面
![test](https://s1.ax1x.com/2022/12/17/zbKEjS.png)

**Comment by MeetWq** [comment]
1. align是按行对齐的，同一行有多个align就会换行，并不是文字align
2. 暂时没有这种功能，你可以一张新建图片并贴上去

**Comment by QwindF** [comment]
谢谢你qwq
