### ISSUE TITLE
机器人运行目录下的 data中无fonts 文件夹

### ISSUE THREAD

**Issue by DGHOSTI** [noneplugin/nonebot-plugin-imageutils#14]
机器人运行目录下的 data中无fonts 文件夹
使用nb plugin install nonebot_plugin_imageutils安装
在使用“头像表情包”插件使用  /头像表情包 后台日志
![QQ截图20230102181515](https://user-images.githubusercontent.com/115383712/210218291-222f542e-479d-428e-8357-9398d76f97fe.png)

**Comment by MeetWq** [comment]
需要安装中文字体，装到系统路径或者放到机器人运行目录下的data/fonts/
