### ISSUE TITLE
Text2Image对象可以直接转成PIL吗

### ISSUE THREAD

**Issue by KarisAya** [noneplugin/nonebot-plugin-imageutils#15]
目前我用的方法是save之后Image.open()打开成PIL
例如

    output = io.BytesIO()
    Text2Image.from_bbcode_text(bg_str, 60, spacing = 10, fontname = fname).to_image("white", (20,20)).save(output, format="png")
    bg = Image.open(output)

感觉在绕路

**Comment by MeetWq** [comment]
to_image 之后就是 Image 啊
