### ISSUE TITLE
BuildImage.open()传入bytes类型时发生错误

### ISSUE THREAD

**Issue by tkgs0** [noneplugin/nonebot-plugin-imageutils#17]
nonebot-plugin-imageutils 版本: 0.1.13.5
Pillow 版本: 9.4.0
Python 版本: 3.10.9

方法 BuildImage.open() 中 file 支持传入 bytes 类型的参数, 当我直接传入 bytes 类型的图像数据时, 控制台报错 ValueError: embedded null byte 
(如下图)
![Screenshot_20230126_230016_com termux](https://user-images.githubusercontent.com/107618388/214873096-3e6d2dba-0f46-4a9d-9fbb-d954acfd0441.jpg)

以下是发生问题的代码
```python3
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys, asyncio
from io import BytesIO
from pathlib import Path
from httpx import AsyncClient
from nonebot_plugin_imageutils import BuildImage

from nonebot.log import logger


filepath = Path(__file__).parent / 'outpix.png'


headers = {
    'Host': 'i.pximg.net',
    'Referer': 'https://www.pixiv.net/',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
}

async def get_url(url, headers = headers, redirects = False):
    async with AsyncClient() as client:
        response = await client.get(
            url,
            headers = headers,
            follow_redirects = redirects,
            timeout = 30
        )
        if response.status_code == 200:
            return response.content


if __name__ == '__main__':
    if len(sys.argv) > 1:
        arg = sys.argv[1]
    else:
        exit(-1)

    content = asyncio.run(get_url(arg))

    if content:
        logger.info('图像下载成功!')
        image = BuildImage.open(content)  # 错误发生的位置
        image.draw_ellipse((3,3,30,30), outline='black')
        filepath.write_bytes(image.save_png().getvalue())
        logger.info('图像保存成功!')
```

测试代码时使用的图像链接 https://i.pximg.net/img-original/img/2018/04/24/01/51/35/68377968_p0.png

但是当我将bytes类型的图像数据转换成BytesIO后再传入open函数时, 代码可以正常运行.

**Comment by MeetWq** [comment]
看了下 PIL 的 Image.open() 的说明，好像是不能直接传 bytes，
所以还是用 BytesIO 转一下吧，我把 type hint 改掉

**Comment by tkgs0** [comment]
> 看了下 PIL 的 Image.open() 的说明，好像是不能直接传 bytes， 所以还是用 BytesIO 转一下吧，我把 type hint 改掉

感谢作者亲的耐心解答🥰, 我也去尝试了一下 PIL 的Image.open() , 发现其 type hint 也是有写 bytes, 但不论是我自己下载的 bytes 数据, 还是用 PIL 自己的函数 Image.tobytes() 生成的 bytes 图像数据, 都会发生 embedded null byte, 或许是他的 type hint 写错了2333
