### ISSUE TITLE
多个\n连起来会误报

### ISSUE THREAD

**Issue by nikissXI** [noneplugin/nonebot-plugin-imageutils#19]
![image](https://user-images.githubusercontent.com/31379266/219301561-7c7a084b-6061-44db-8a5d-e611c70e7e68.png)
![image](https://user-images.githubusercontent.com/31379266/219301692-1565e857-d7b8-4505-a400-385e7c377dc2.png)

bg_str = f"\n\n"
bg = Text2Image.from_bbcode_text(bg_str, 60, spacing=10, fontname=fname).to_image("white", (20, 20))

如果\n之间加个空格就没事

**Comment by MeetWq** [comment]
逝世新版

**Comment by nikissXI** [comment]
> 逝世新版

彳亍
