### ISSUE TITLE
windows下的换行会显示为方块

### ISSUE THREAD

**Issue by jenying1107** [noneplugin/nonebot-plugin-imageutils#2]
windows输入的换行是\r\n，这个时候调用draw_text方法换行会显示为方块□。
经过测试，linux、安卓下的换行符\n没有这个问题。

**Comment by MeetWq** [comment]
https://github.com/noneplugin/nonebot-plugin-imageutils/commit/610c2915c247bd65bbbe4fffe258c9086afdbb7b

**Comment by jenying1107** [comment]
修复了，感谢大佬qwq
