### ISSUE TITLE
BuildImage.circle_corner()生成的圆角矩形以及.circle()生成的圆形四角有黑色边缘

### ISSUE THREAD

**Issue by LambdaYH** [noneplugin/nonebot-plugin-imageutils#20]
如图
![8FR4N1QY3$YVR~{KU2U4DM5](https://user-images.githubusercontent.com/13503375/219332214-f022279e-7691-4960-9c39-3ccd17a959bf.PNG)
![%I2Y4I}{99}9WJ70E9OJ@JA](https://user-images.githubusercontent.com/13503375/219332654-d106d28a-4452-441a-abc2-a5397db870d8.PNG)

测试代码如下：
```python
from nonebot import on_fullmatch
from nonebot.adapters.onebot.v11 import MessageSegment

from nonebot_plugin_imageutils import BuildImage

test = on_fullmatch("圆角矩形", priority=5, block=True)


@test.handle()
async def _():
    text_img = BuildImage.new(mode="RGBA", size=(80, 80), color=(230,230,230)).circle_corner(r=20)
    # text_img = BuildImage.new(mode="RGBA", size=(80, 80), color=(230,230,230)).circle()
    bg_img = BuildImage.new(mode="RGBA", size=(200, 200), color="white")
    bg_img.paste(text_img, pos=(20, 20), alpha=True)
    await test.send(MessageSegment.image(bg_img.save_png()))
```

**Comment by MeetWq** [comment]
逝世新版

**Comment by LambdaYH** [comment]
白色背景下没黑边了，但是非白色背景下出现了白色不透明四角（
![LJG)$53UVW{PLFWT}SUHR`Q](https://user-images.githubusercontent.com/13503375/219555724-97fed629-05db-467a-b295-07417b5a0370.PNG)
```python
@test.handle()
async def _():
    text_img = BuildImage.new(
        mode="RGBA", size=(80, 80), color=(230, 230, 230)).circle_corner(r=20)
    # text_img = BuildImage.new(mode="RGBA", size=(80, 80), color=(230,230,230)).circle()
    bg_img = BuildImage.new(mode="RGBA", size=(200, 200), color=(128, 128, 128))
    bg_img.paste(text_img, pos=(20, 20), alpha=True)
    await test.send(MessageSegment.image(bg_img.save_png()))
```

------------------
https://github.com/noneplugin/nonebot-plugin-imageutils/blob/3b758df50b9b3ba0f8ac4773dbdcbe833a3ebebe/nonebot_plugin_imageutils/build_image.py#L155
https://github.com/noneplugin/nonebot-plugin-imageutils/blob/3b758df50b9b3ba0f8ac4773dbdcbe833a3ebebe/nonebot_plugin_imageutils/build_image.py#L165
这里改成
```python
bg = Image.new("RGBA", image.size, (255, 255, 255, 0))
```
似乎就正常了

**Comment by MeetWq** [comment]
雀食

**Comment by MeetWq** [comment]
已经改了
