### ISSUE TITLE
报错TypeError: Object of type Image is not JSON serializable

### ISSUE THREAD

**Issue by KarisAya** [noneplugin/nonebot-plugin-imageutils#4]
代码大概长这个样子...
`img = Text2Image.from_text("@mnixry 🤗", 50).to_image()`
`await company_info.finish(MessageSegment.image(img))`
![T~%{{$9OZ(37WP~((QHTQ69](https://user-images.githubusercontent.com/51886078/180981780-5e5d180f-4224-4fe8-b9b9-9b45ac558460.png)
![{%_LP`QM_%T)IO7}QT8YX29](https://user-images.githubusercontent.com/51886078/180981803-89a1295f-00b3-4c3c-8fc5-93ca6351f2ec.png)

**Comment by MeetWq** [comment]
Text2Image 出来是 PIL 的 Image 格式，不能直接发送，我更新了 readme 说明了，可以看看
