### ISSUE TITLE
ValueError: bad transparency mask

### ISSUE THREAD

**Issue by Ealvn** [noneplugin/nonebot-plugin-imageutils#5]
关于大佬更新的v0.1.8版本，在被同样是大佬写的 [nonebot-plugin-petpet](https://github.com/noneplugin/nonebot-plugin-petpet) 项目中的 [字符画函数](https://github.com/noneplugin/nonebot-plugin-petpet/blob/bcb3de84f7d95b9a6bdba079a3a108d5ae5d0eb2/nonebot_plugin_petpet/functions.py#L1299) 调用时报错，其他功能的函数貌似正常

报错如下：
![QQ图片20220816013034](https://user-images.githubusercontent.com/39033468/184744415-e9977dbe-1410-49a5-82ee-441cf63a2a76.png)

好像是 [01fe3aa](https://github.com/noneplugin/nonebot-plugin-imageutils/commit/01fe3aa8d94b62dd860e24d8975594f1133d40f6) 新改的save_jpg()和charpic()不兼容，经测试换回v0.1.7版的save_jpg()后就可以使用了

**Comment by MeetWq** [comment]
感谢反馈，已经修了
