### ISSUE TITLE
插件连接字体失败 Can not load face.  Unknown file format.

### ISSUE THREAD

**Issue by FairyReimu** [noneplugin/nonebot-plugin-imageutils#7]
启动机器人后，出现以下提示信息：

nonebot_plugin_imageutils | Failed to extract font properties from data/fonts/current_NotoColorEmoji.ttf: In FT2Font: Can not load face.  Unknown file format.
08-30 12:25:27 [WARNING] nonebot_plugin_imageutils | Failed to extract font properties from data/fonts/NotoColorEmoji.ttf: In FT2Font: Can not load face.  Unknown file format.

更换过字体文件也是同样的报错
然后部分制图的插件出现中文变成□□，不知道是否是受此影响

**Comment by MeetWq** [comment]
emoji字体比较特殊，建议通过
```
sudo apt install fonts-noto-color-emoji
```
来安装

中文显示不了和这个字体没关系

**Comment by FairyReimu** [comment]
好的，感谢解答
