### ISSUE TITLE
`BuildImage.circle_corner` 方法处理半透明图片时被切割的角落会变得不透明

### ISSUE THREAD

**Issue by lgc2333** [noneplugin/nonebot-plugin-imageutils#9]
如图

![IMG20221014144614](https://user-images.githubusercontent.com/59048777/195780793-c0231e22-67f1-4512-a98a-8582aba371a0.jpg)

**Comment by MeetWq** [comment]
可以提供这种情况的代码吗？

**Comment by lgc2333** [comment]
> 可以提供这种情况的代码吗？

https://github.com/lgc2333/nonebot-plugin-bawiki/blob/master/nonebot_plugin_bawiki/data_gamekee.py#L190
将`p`替换为`p.circle_corner()`应该就会出现

**Comment by MeetWq** [comment]
新版改了，逝世看行不行
